project_name = "sophon"
bootstraps = ["/dns/bootnode.1.lightclient.mainnet-mmp.avail.so/tcp/37000/p2p/12D3KooWHgPbEYcvZvZz4aT3KiBdjQmphG5qJ9StWoUps1ofKbJx"]
full_node_ws = ["wss://mainnet.avail-rpc.com", "wss://avail.api.onfinality.io/public-ws", "wss://avail-us.brightlystake.com", "wss://avail-rpc.publicnode.com"]
genesis_hash = "b91746b45e0346cc2f815a520b9c6cb4d5c0902af848db0a80f85932d2e8276a"
ot_collector_endpoint = "http://otel.lightclient.sophon.avail.so:4317"
http_server_port = 7007
http_server_host = "0.0.0.0"
block_processing_delay = 20
sophon_minimum_required_version = "0.0.90"
